name: dsg
description: "Static site generator. Supports markdown, mustache, partials, assets, sass. Webserver included."
homepage: https://github.com/maks/dsg

version: 2.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add the bin/sitegen.dart script to the scripts pub installs.
# Activate local repo:
#   pub global activate --source path .
#
executables:
  dsg:

dependencies:
  args: ^2.4.2
  checks: ^0.2.2
  bonsai: ^1.0.1
  yaml: ^3.1.2
  path: ^1.8.3
  markdown: ^7.1.0
  mustache_template: ^2.0.0
  intl: ^0.18.1
  http_server: ^1.0.0
  system_info_ml: ^1.0.0
  watcher: ^1.1.0
  front_matter_ml: ^1.2.0
    
dev_dependencies:
  test: any
  grinder: any
  build_runner: any
  build_test: any